config/routes.rb
Rails.application.routes.draw do
  resources :evenements
  root to: 'high_voltage/pages#show', id: 'home'
end

app/models/evenement.rb
class Evenement < ActiveRecord::Base

  validates_presence_of :name, message: 'Champ obligatoire'
  validates_presence_of :date, message: 'Champ obligatoire'
  validates_presence_of :email, message: 'Champ obligatoire'
  validates_format_of :email,
                      with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i,
                      message: "L'adresse email est invalide"

  validates_presence_of :description, message: 'Champ obligatoire'
  validates_length_of :description, :maximum => 300, message: 'Trop long, maximum 300 caractères'

  def self.futurs
    where("DATE(date) >= ?", Date.today)
  end

  def date_fr
    date.strftime('%d/%m/%Y') if !date.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_evenement, only: [:show, :edit, :update, :destroy]

  # GET /evenements
  # GET /evenements.json
  def index
    @evenements = Evenement.futurs.order(sort_column + " " + sort_direction)
  end

  # GET /evenements/1
  # GET /evenements/1.json
  def show
  end

  # GET /evenements/new
  def new
    @evenement = Evenement.new
  end

  # GET /evenements/1/edit
  def edit
  end

  # POST /evenements
  # POST /evenements.json
  def create
    @evenement = Evenement.new(evenement_params)

    respond_to do |format|
      if @evenement.save
        format.html { redirect_to @evenement, notice: 'L\'événement à été créé' }
        format.json { render :show, status: :created, location: @evenement }
      else
        format.html { render :new }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evenements/1
  # PATCH/PUT /evenements/1.json
  def update
    respond_to do |format|
      if @evenement.update(evenement_params)
        format.html { redirect_to @evenement, notice: 'L\'événement à été mis à jour'  }
        format.json { render :show, status: :ok, location: @evenement }
      else
        format.html { render :edit }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evenements/1
  # DELETE /evenements/1.json
  def destroy
    @evenement.destroy
    respond_to do |format|
      format.html { redirect_to evenements_url, alert: 'L\'événement à été supprimé' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evenement
      @evenement = Evenement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evenement_params
      params.require(:evenement).permit(:name, :date, :email, :description)
    end

    #Get parameter sort if it matches a columns name
    def sort_column
      Evenement.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

    #Get parameter direction if it asc or desc
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title , {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/views/evenements/_form.html.erb
<%= simple_form_for(@evenement) do |f| %>
  <%= f.error_notification message: 'Certains champs comportent des erreurs. Merci de vérifier votre saisie',
                           class: 'alert alert-danger' %>

  <div class="form-inputs">
    <%= f.input :name, autofocus: true, label: 'Nom' %>
    <%= f.input :date, as: :string, input_html: {class: 'bootstrap-datepicker', value: f.object.date_fr } %>
    <%= f.input :email %>
    <%= f.input :description, label: 'Description (300 caractères max)' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: 'Enregistrer', class: 'btn btn-sm btn-primary' %>
  </div>
<% end %>

app/views/evenements/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Editer l'événement</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>

</div>
  <%= link_to 'Afficher', @evenement, class: 'btn btn-sm btn-primary' %>
  <%= link_to 'Retour à la liste', evenements_path, class: 'btn btn-sm btn-default' %>

app/views/evenements/index.html.erb
<h1>Liste des événements</h1>
<div class="col-md-12">
  <table class="table table-hover sortable">
    <thead>
    <tr>
      <th><%= sortable "name", "Nom" %></th>
      <th><%= sortable "date", "Date" %></th>
      <th><%= sortable "email", "Email organisateur" %></th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @evenements.each do |evenement| %>
        <tr>
          <td<%= evenement.date < 1.week.from_now ? ' class="upcoming"'.html_safe : '' %>><%= evenement.name %></td>
          <td><%= evenement.date_fr %></td>
          <td><%= evenement.email %></td>
          <td><%= highlight evenement.description, ['roue', 'peigne', 'chat', 'table'], highlighter: '<span class="highlighted">\1</span>' %></td>
          <td><%= link_to 'Voir', evenement, class: 'btn btn-sm btn-default' %></td>
          <td><%= link_to 'Editer', edit_evenement_path(evenement), class: 'btn btn-sm btn-primary' %></td>
          <td><%= link_to 'Supprimer', evenement,
                          method: :delete,
                          data: {confirm: 'Etes vous certain de vouloir supprimer l\'événement?'},
                          class: 'btn btn-sm btn-danger' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Nouvel événement', new_evenement_path, class: 'btn btn-sm btn-primary' %>

app/views/evenements/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Nouvel événement</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to 'Retour à la liste', evenements_path, class: 'btn btn-sm btn-default' %>

app/views/evenements/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Evénement</h3>
  </div>
  <div class="panel-body"><p>
    <strong>Nom :</strong>
    <%= @evenement.name %>
  </p>

    <p>
      <strong>Date :</strong>
      <%= @evenement.date_fr %>
    </p>

    <p>
      <strong>Email organisateur :</strong>
      <%= @evenement.email %>
    </p>

    <p>
      <strong>Description :</strong>
      <%= @evenement.description %>
    </p>
  </div>
</div>
<%= link_to 'Editer', edit_evenement_path(@evenement), class: 'btn btn-sm btn-primary' %>
<%= link_to 'Retour', evenements_path, class: 'btn btn-sm btn-default' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for bootstrap 3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert <%= name.to_s == 'notice' ? 'alert-success' : 'alert-danger' %>">
      <%= content_tag :div, msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for bootstrap 3%>
<nav class="navbar navbar-inverse navbar-fixed-top" data-topbar>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= url_for root_path %>">Project name</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Evenements', evenements_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<div class="container">
  <div class="page-content">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/pages/home.html.erb
<% content_for :title do %>About
<% end %>
<h3>Bienvenue</h3>

<div class="col-md-6">
  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
    standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a
    type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
    remaining
    essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
    passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem
    Ipsum.</p>
</div>
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Evénements</h3>
    </div>
    <div class="panel-body">
      <%= link_to 'Liste des événements', evenements_path, class: 'btn btn-default'  %>
      <%= link_to 'Ajouter un événement', new_evenement_path, class: 'btn btn-primary'  %>
    </div>
  </div>
</div>